name: Continuous Deployment

on:
  workflow_run:
    workflows: ["Continuous Integration (Testing and Load Test)"]  # This should match the name of your CI workflow (ci.yml)
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}  # Run only if CI succeeds

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ec2-user@15.207.98.242 << 'EOF'
            cd Task1_Sample_Project || git clone https://github.com/abhinav059/Task1_Sample_Project.git && cd Task1_Sample_Project
            git pull origin main
            npm install
            pm2 restart index.js || pm2 start index.js
            echo "Deployment Successful!"
          EOF

  rollback:
    runs-on: ubuntu-latest
    if: ${{ failure() }}

    steps:
      - name: Setup SSH
        run: |
          echo "-----BEGIN RSA PRIVATE KEY-----
          ...
          -----END RSA PRIVATE KEY-----" > private_key.pem
          chmod 600 private_key.pem

      - name: Rollback on Failure
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ec2-user@15.207.98.242 << 'EOF'
            echo "Deployment Failed. Rolling back..."
            cd Task1_Sample_Project
            git reset --hard HEAD~1
            npm install
            pm2 restart index.js
            echo "Rollback Completed!"
          EOF



      # - name: Deploy to EC2
      #   run: |
      #     ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
      #       cd Task1_Sample_Project || git clone https://github.com/abhinav059/Task1_Sample_Project.git && cd Task1_Sample_Project
      #       git pull origin main
      #       npm install
      #       pm2 restart index.js || pm2 start index.js
      #       echo "Deployment Successful!"
      #     EOF
